# config/routes.yaml
admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

main:
    # loads routes from the given routing file stored in some bundle
    resource: 'routes/main.yaml'


